spring.application.name=Kafka.consumer
server.port=8082
#Producer
#|
#| JSON Message
#v
#Kafka Topic
#|
#v
#Consumer
#
#1. Key Deserializer
#byte[] -> String
#
#2. JacksonJsonDeserializer
#JSON -> Java Object
#
#3. trusted.packages
#Check package is trusted
#
#4. default.type
#Create OrderEvent object
#
#5. @KafkaListener receives:
#
#public void consume(OrderEvent event)
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=notification-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer //like byte to obj

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*// trust all pckg convert obj

spring.kafka.consumer.properties.spring.json.value.default.type=com.notification_service.dto.OrderEvent
