spring.application.name=Producer

server.port=8081

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer


#OrderEvent Object
#|
#| StringSerializer
#| Key -> byte[]
#|
#| JacksonJsonSerializer
#| Object -> JSON
#v
#Kafka Broker (9092)
#|
#v
#order-events Topic